.TH "PuzzleRoom" 3 "Sat Nov 14 2015" "Version 0.1" "Orque" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PuzzleRoom \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PuzzleRoom\&.h>\fP
.PP
Inherits \fBRoom\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPuzzleRoom\fP (std::string, int *)"
.br
.ti -1c
.RI "\fBPuzzleRoom\fP (const \fBPuzzleRoom\fP &)"
.br
.ti -1c
.RI "\fBRoom\fP * \fBclone\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "std::string \fBprintAdjList\fP ()"
.br
.ti -1c
.RI "std::string \fBgetID\fP ()"
.br
.ti -1c
.RI "int * \fBgetAdjacencyList\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Puzzle \fBRoom\fP class
.PP
Uses \fBRoom()\fP Base Class Requires Boost C++ Library 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PuzzleRoom::PuzzleRoom (const \fBPuzzleRoom\fP & pPuzzleRoom)"
Copy Constructor for \fBPuzzleRoom\fP
.PP
Parameters: \fBPuzzleRoom\fP& pPuzzleRoom - instance of \fBPuzzleRoom\fP to copy 
.SH "Member Function Documentation"
.PP 
.SS "\fBRoom\fP * PuzzleRoom::clone ()\fC [virtual]\fP"
\fBclone()\fP
.PP
clone function for \fBPuzzleRoom\fP
.PP
Returns: cloned instance of \fBPuzzleRoom\fP 
.PP
Implements \fBRoom\fP\&.
.SS "void PuzzleRoom::print ()\fC [virtual]\fP"
\fBprint()\fP
.PP
Prints information about the current instance of \fBPuzzleRoom\fP 
.PP
Implements \fBRoom\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Orque from the source code\&.
