.TH "Room" 3 "Sat Nov 14 2015" "Orque" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Room \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Room\&.h>\fP
.PP
Inherited by \fBPuzzleRoom\fP, and \fBRegularRoom\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBRoom\fP * \fBclone\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBprint\fP ()=0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Prototype for \fBRoom\fP classes
.PP
Base class for \fBRegularRoom\fP, \fBPuzzleRoom\fP, and TrapRoom Requires Boost C++ Library 

.SH "Author"
.PP 
Generated automatically by Doxygen for Orque from the source code\&.
